[package]
name = "graph_loom"
version = "0.1.0"
edition = "2024"

[dependencies]

# GUI
eframe = "0.33.3"
egui = "0.33.3"

# Utils
env_logger = { version = "0.11.8", default-features = false }
uuid = { version = "1", features = ["v7", "fast-rng", "serde"] }
serde = { version = "1", features = ["derive"] }
ron = "0.12.0"
time = { version = "0.3", features = ["formatting", "macros"] }
anyhow = "1"
serde_json = "1"
csv = "1"